// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Amante das Palavras de Afeto - Onde o amor é escrito à mão",
  description: "Plataforma de emoção, escrita e conexão. Publique cartas de amor, bilhetes e poesias. Encomende textos personalizados escritos com o coração.",
  keywords: "cartas de amor, poesias, bilhetes românticos, escrita afetiva, correspondência, romantismo",
  authors: [{ name: "Paulo - Amante das Palavras de Afeto" }],
  openGraph: {
    title: "Amante das Palavras de Afeto",
    description: "Onde o amor é escrito à mão. Junte-se a uma comunidade que acredita no poder das palavras escritas com o coração.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-serif`}
      >
        {children}
      </body>
    </html>
  );
}